title: Minerva Fasttrack Group Ecophotonics
page-top-title: Ecophotonics Lab
top-section-bg-text: Bio-based and living matter for functional photonics
home-subtitle: Welcome to the website of the Ecophotonics Lab!
copyright-text: '&copy; Vera Titze 2026. All Rights Reserved.'
